#include "Features/Systems/Rendering/Profile/ProfileSlice.h"

#include "Core/fp.hpp"

namespace ForbocAI {
namespace Game {
namespace Level {
namespace RenderingProfileReducers {

/** User Story: As a systems rendering profile consumer, I need to invoke reduce runtime profile through a stable signature so the systems rendering profile workflow remains explicit and composable. @fn FLevelRetroRenderProfile ReduceRuntimeProfile( const ForbocAI::Game::Data::FProfileSettings &Settings) */
FLevelRetroRenderProfile ReduceRuntimeProfile(
    const ForbocAI::Game::Data::FProfileSettings &Settings) {
  return {Settings.TimeOfDayHour,
          Settings.AntiAliasingMethod,
          Settings.PostProcessAAQuality,
          Settings.ScreenPercentage,
          Settings.MinimumScreenPercentage,
          Settings.InternalRenderWidth,
          Settings.InternalRenderHeight,
          Settings.OutputScaleMultiplier,
          Settings.bFullscreenOutput,
          Settings.RuntimeResolutionCommandFormat,
          Settings.FullscreenOutputSuffix,
          Settings.WindowedOutputSuffix,
          Settings.ScreenPercentageCVarName,
          Settings.RuntimeOutputLogFormat,
          Settings.RuntimeOutputFormatBufferCharacterCount,
          Settings.ViewDistanceScale,
          Settings.FoliageDensityScale,
          Settings.GrassDensityScale,
          Settings.SunPitchDegrees,
          Settings.SunYawDegrees,
          Settings.SunRollDegrees,
          Settings.DirectionalLightIntensity,
          Settings.DirectionalLightSourceAngle,
          Settings.DirectionalLightColorR,
          Settings.DirectionalLightColorG,
          Settings.DirectionalLightColorB,
          Settings.DirectionalLightColorA,
          Settings.ShadowCascades,
          Settings.ShadowMaxResolution,
          Settings.PostProcessPriority,
          Settings.PostProcessBlendRadius,
          Settings.PostProcessBlendWeight,
          Settings.PostProcessEnabledBlendWeightThreshold,
          Settings.RuntimePostProcessActorTag,
          Settings.PostProcessSaturationMultiplier,
          Settings.PostProcessContrastMultiplier,
          Settings.PostProcessGainR,
          Settings.PostProcessGainG,
          Settings.PostProcessGainB,
          Settings.PostProcessGainA,
          Settings.PostProcessSceneTintR,
          Settings.PostProcessSceneTintG,
          Settings.PostProcessSceneTintB,
          Settings.PostProcessSceneTintA,
          Settings.SkyAtmosphereSkyLuminanceR,
          Settings.SkyAtmosphereSkyLuminanceG,
          Settings.SkyAtmosphereSkyLuminanceB,
          Settings.SkyAtmosphereSkyLuminanceA,
          Settings.SkyAtmosphereAerialLuminanceR,
          Settings.SkyAtmosphereAerialLuminanceG,
          Settings.SkyAtmosphereAerialLuminanceB,
          Settings.SkyAtmosphereAerialLuminanceA,
          Settings.SkyAtmosphereHeightFogContribution,
          Settings.SkyLightIntensity,
          Settings.SkyLightColorR,
          Settings.SkyLightColorG,
          Settings.SkyLightColorB,
          Settings.SkyLightColorA,
          Settings.bSkyLightRealTimeCapture,
          Settings.bSkyDomeEnabled,
          Settings.SkyDomeMeshPath,
          Settings.SkyDomeMaterialPath,
          Settings.SkyDomeScale,
          Settings.SkyDomeZOffset,
          Settings.SkyDomeSkyBrightness,
          Settings.SkyDomeCloudBrightness,
          Settings.SkyDomeCloudDarkness,
          Settings.SkyDomeRimBrightness,
          Settings.SkyDomeStarColorR,
          Settings.SkyDomeStarColorG,
          Settings.SkyDomeStarColorB,
          Settings.SkyDomeStarColorA,
          Settings.SkyDomeHorizonColorR,
          Settings.SkyDomeHorizonColorG,
          Settings.SkyDomeHorizonColorB,
          Settings.SkyDomeHorizonColorA,
          Settings.SkyDomeZenithColorR,
          Settings.SkyDomeZenithColorG,
          Settings.SkyDomeZenithColorB,
          Settings.SkyDomeZenithColorA,
          Settings.bMoonDiscEnabled,
          Settings.MoonDiscMeshPath,
          Settings.MoonDiscMaterialPath,
          Settings.MoonDiscDistance,
          Settings.MoonDiscScale,
          Settings.MoonDiscPitchDegrees,
          Settings.MoonDiscYawDegrees,
          Settings.MoonDiscRollDegrees,
          Settings.MoonDiscColorR,
          Settings.MoonDiscColorG,
          Settings.MoonDiscColorB,
          Settings.MoonDiscColorA,
          Settings.MoonPixelGridSize,
          Settings.MoonDiscWorldUnitsPerScale,
          Settings.MoonPixelOverlapMultiplier,
          Settings.PointStarCount,
          Settings.PointStarYawHashSalt,
          Settings.PointStarYawSpanDegrees,
          Settings.PointStarPitchHashSalt,
          Settings.PointStarPitchMinDegrees,
          Settings.PointStarPitchSpanDegrees,
          Settings.PointStarDistanceMultiplier,
          Settings.PointStarSizeHashSalt,
          Settings.PointStarWorldSizeMin,
          Settings.PointStarWorldSizeJitter,
          Settings.MoonPixelGridTerminalOffset,
          Settings.MoonPixelVisibleRadius,
          Settings.PointStarHashIndexOffset,
          Settings.PointStarHashMultiplier,
          Settings.PointStarRollDegrees,
          Settings.RuntimeSkyDomeActorTag,
          Settings.RuntimeMoonDiscActorTag,
          Settings.RuntimePointStarsActorTag,
          Settings.RuntimeMoonPixelsComponentName,
          Settings.RuntimePointStarsComponentName,
          Settings.MaterialBaseColorParameter,
          Settings.MaterialColorParameter,
          Settings.MaterialTintColorParameter,
          Settings.MaterialDiffuseColorParameter,
          Settings.MaterialEmissiveColorParameter,
          Settings.SkyDomeSkyBrightnessParameter,
          Settings.SkyDomeCloudBrightnessParameter,
          Settings.SkyDomeCloudDarknessParameter,
          Settings.SkyDomeRimBrightnessParameter,
          Settings.SkyDomeStarsParameter,
          Settings.SkyDomeStarColorParameter,
          Settings.SkyDomeHorizonColorParameter,
          Settings.SkyDomeZenithColorParameter,
          Settings.SkyDomeStarsScalarValue,
          Settings.SkyDomeTextureStarMaskColorR,
          Settings.SkyDomeTextureStarMaskColorG,
          Settings.SkyDomeTextureStarMaskColorB,
          Settings.SkyDomeTextureStarMaskColorA,
          Settings.RuntimePixelMeshSectionIndex,
          Settings.RuntimePixelMaterialIndex,
          Settings.PixelQuadHalfExtentMultiplier,
          Settings.PixelQuadIndexA,
          Settings.PixelQuadIndexB,
          Settings.PixelQuadIndexC,
          Settings.PixelQuadIndexD,
          Settings.PixelQuadUvMin,
          Settings.PixelQuadUvMax,
          Settings.bFogEnabled,
          Settings.bVolumetricFogEnabled,
          Settings.FogDensity,
          Settings.FogHeightFalloff,
          Settings.FogStartDistance,
          Settings.FogCutoffDistance,
          Settings.FogMaxOpacity,
          Settings.FogColorR,
          Settings.FogColorG,
          Settings.FogColorB,
          Settings.FogColorA};
}

} // namespace RenderingProfileReducers
} // namespace Level
} // namespace Game
} // namespace ForbocAI
