#include "Features/Systems/Rendering/Profile/ProfileSlice.h"

#include "Core/ue_fp.hpp"

namespace ForbocAI {
namespace Game {
namespace Level {
namespace RenderingProfileReducers {

FLevelRetroRenderProfile ReduceRuntimeProfile(
    const ForbocAI::Game::Data::FProfileSettings &Settings) {
  return {Settings.TimeOfDayHour,
          Settings.AntiAliasingMethod,
          Settings.PostProcessAAQuality,
          Settings.ScreenPercentage,
          Settings.MinimumScreenPercentage,
          Settings.InternalRenderWidth,
          Settings.InternalRenderHeight,
          Settings.OutputScaleMultiplier,
          Settings.bFullscreenOutput,
          Settings.ViewDistanceScale,
          Settings.FoliageDensityScale,
          Settings.GrassDensityScale,
          Settings.SunPitchDegrees,
          Settings.SunYawDegrees,
          Settings.SunRollDegrees,
          Settings.DirectionalLightIntensity,
          Settings.DirectionalLightSourceAngle,
          Settings.DirectionalLightColorR,
          Settings.DirectionalLightColorG,
          Settings.DirectionalLightColorB,
          Settings.DirectionalLightColorA,
          Settings.ShadowCascades,
          Settings.ShadowMaxResolution,
          Settings.PostProcessPriority,
          Settings.PostProcessBlendRadius,
          Settings.PostProcessBlendWeight,
          Settings.PostProcessSaturationMultiplier,
          Settings.PostProcessContrastMultiplier,
          Settings.PostProcessGainR,
          Settings.PostProcessGainG,
          Settings.PostProcessGainB,
          Settings.PostProcessGainA,
          Settings.PostProcessSceneTintR,
          Settings.PostProcessSceneTintG,
          Settings.PostProcessSceneTintB,
          Settings.PostProcessSceneTintA,
          Settings.SkyAtmosphereSkyLuminanceR,
          Settings.SkyAtmosphereSkyLuminanceG,
          Settings.SkyAtmosphereSkyLuminanceB,
          Settings.SkyAtmosphereSkyLuminanceA,
          Settings.SkyAtmosphereAerialLuminanceR,
          Settings.SkyAtmosphereAerialLuminanceG,
          Settings.SkyAtmosphereAerialLuminanceB,
          Settings.SkyAtmosphereAerialLuminanceA,
          Settings.SkyAtmosphereHeightFogContribution,
          Settings.SkyLightIntensity,
          Settings.SkyLightColorR,
          Settings.SkyLightColorG,
          Settings.SkyLightColorB,
          Settings.SkyLightColorA,
          Settings.bSkyLightRealTimeCapture,
          Settings.bSkyDomeEnabled,
          Settings.SkyDomeMeshPath,
          Settings.SkyDomeMaterialPath,
          Settings.SkyDomeScale,
          Settings.SkyDomeZOffset,
          Settings.SkyDomeSkyBrightness,
          Settings.SkyDomeCloudBrightness,
          Settings.SkyDomeCloudDarkness,
          Settings.SkyDomeRimBrightness,
          Settings.SkyDomeStarColorR,
          Settings.SkyDomeStarColorG,
          Settings.SkyDomeStarColorB,
          Settings.SkyDomeStarColorA,
          Settings.SkyDomeHorizonColorR,
          Settings.SkyDomeHorizonColorG,
          Settings.SkyDomeHorizonColorB,
          Settings.SkyDomeHorizonColorA,
          Settings.SkyDomeZenithColorR,
          Settings.SkyDomeZenithColorG,
          Settings.SkyDomeZenithColorB,
          Settings.SkyDomeZenithColorA,
          Settings.bMoonDiscEnabled,
          Settings.MoonDiscMeshPath,
          Settings.MoonDiscMaterialPath,
          Settings.MoonDiscDistance,
          Settings.MoonDiscScale,
          Settings.MoonDiscPitchDegrees,
          Settings.MoonDiscYawDegrees,
          Settings.MoonDiscRollDegrees,
          Settings.MoonDiscColorR,
          Settings.MoonDiscColorG,
          Settings.MoonDiscColorB,
          Settings.MoonDiscColorA,
          Settings.MoonPixelGridSize,
          Settings.MoonDiscWorldUnitsPerScale,
          Settings.MoonPixelOverlapMultiplier,
          Settings.PointStarCount,
          Settings.PointStarYawHashSalt,
          Settings.PointStarYawSpanDegrees,
          Settings.PointStarPitchHashSalt,
          Settings.PointStarPitchMinDegrees,
          Settings.PointStarPitchSpanDegrees,
          Settings.PointStarDistanceMultiplier,
          Settings.PointStarSizeHashSalt,
          Settings.PointStarWorldSizeMin,
          Settings.PointStarWorldSizeJitter,
          Settings.bFogEnabled,
          Settings.bVolumetricFogEnabled,
          Settings.FogDensity,
          Settings.FogHeightFalloff,
          Settings.FogStartDistance,
          Settings.FogCutoffDistance,
          Settings.FogMaxOpacity,
          Settings.FogColorR,
          Settings.FogColorG,
          Settings.FogColorB,
          Settings.FogColorA};
}

} // namespace RenderingProfileReducers
} // namespace Level
} // namespace Game
} // namespace ForbocAI
